### ISSUE TITLE
gatsby-remark-images-anywhere breaks if markdown contains HTML element or a gatsby-transformer-remark custom component

### ISSUE THREAD

**Issue by fartinmartin** [d4rekanguok/gatsby-remark-images-anywhere#3]
If your markdown contains an HTML element or a `gatsby-transformer-remark` custom component you will receive this error:

```Cannot read property 'attrs' of undefined```

However, it seems you can use a custom component _after_ `gatsby-remark-images-anywhere` runs since #2 works.

**Comment by d4rekanguok** [comment]
Hey @fartinmartin, thanks for using this plugin & filing issues in the last few days! I'll try to reproduce these issues & see how they can be fixed.

**Comment by d4rekanguok** [comment]
Reading more into the issue, i think this is the [problematic line](https://github.com/d4rekanguok/gatsby-remark-images-anywhere/blob/581cf5766596635c8ca8d9470a77b9237f7a5686/src/util-html-to-md.ts#L10).

I think adding a null check for `attrs` will resolve this. Will fix this when I have the chance, but if you want to send a PR over it is hugely appreciated!!

**Comment by fartinmartin** [comment]
Wow—you're a genius, haha! This was my first PR, so thanks for letting me collaborate 😀

**Comment by d4rekanguok** [comment]
If I were a genius I wouldn't had left this huge bug in the repo 😅 thank you again! I'm also honored that your first PR is for a project of mine -- Have fun coding!
